### ISSUE TITLE
why does S2 has 3 channels?why not four?

### ISSUE THREAD

**Issue by toohappygirl** [tofuai/neoplasm-segmentation#2]
In your blazeno.model:S2 has 3 three channels,i don't understand.
Could you please explain it for me？
Or this depends on which  dataset you use?when use NeoPloyp dataset, S2 has 4 channels;when NeoPloyp-Clean dataset,this will be 3?

**Comment by tofuai** [comment]
For the NeoPolyp dataset, which is private, 4 channel is for 4 class: neoplastic, non-neoplastic, undefined, and background
For the NeoPolyp-Clean dataset (partly public on Kaggle), 3 channel is for 3 class: neoplastic, non-neoplastic, and background.
There is an undefined region because the doctor can not label it as a neoplastic or non-neoplastic polyp from the image.
